# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DeteccionDePalmeras
                                 A QGIS plugin
 Este plug-in permite detectar automáticamente 3 especies de palmeras en imágenes RGB adquiridas con RPAs:aguaje (Mauritia flexuosa), huasai (Euterpe precautoria) y ungurahui (Oenocarpus bataua). 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-10-06
        copyright            : (C) 2021 by Susan Palacios, Rodolfo Cardenas,  Stephano Torres, Ximena Tagle
        email                : rcardenasv@iiap.gob.pe
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Susan Palacios, Rodolfo Cardenas, Stephano Torres, Ximena Tagle'
__date__ = '2025-10-24'
__copyright__ = '(C) 2025 by Susan Palacios, Rodolfo Cardenas, Stephano Torres, Ximena Tagle'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DeteccionDePalmeras class from file DeteccionDePalmeras.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    # Before creating the plugin instance, ensure external (non-QGIS)
    # dependencies are present. If not, show a small installer UI that
    # can attempt to install missing packages using pip --no-deps.

    from .deteccion_de_palmeras import DeteccionDePalmerasPlugin
    return DeteccionDePalmerasPlugin(iface)
